apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-config
  namespace: uaa-system
data:
  uaa.yml: |
    issuer:
      uri: http://uaa.uaa-system.svc.cluster.local:8080/uaa
    
    spring_profiles: hsqldb
    
    database:
      url: jdbc:hsqldb:mem:uaa
      username: ""
      password: ""
      
    jwt:
      token:
        policy:
          activeKeyId: uaa-jwt-key-1
          keys:
            uaa-jwt-key-1:
              signingKey: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIEowIBAAKCAQEA4f5wg5l2hKsTeNem/V41fGnJm6gOdrj8ym3rFkEjWT2btf0n
                T8eLlObvhz7+IWjqqT5mg1x8w+4dJJqCfqlFNGLNUfawwKvKQGOGCYgXdNjOmDnK
                PBN0wQ3AGJP8k0tWAWFP+WUXQ+SjC+sVIqLGBF8YlVUe5s6oGC7YGgtxFDcyqL8C
                D5UlBKU8L7k2FQVF4P8VYXYCePd7eeQ8JjMq1qO+/3eOJGpGnQqAHhQJwaDnGKJg
                HElh8lBV5gGHQw6AJLXObtNVAAKQnCILQUm+GUklJRHEfATPgQdtDUL/2k8MJj9a
                FrMOuqHM4QQ3cUAJCwOy5z9iJ0E6TKVYV8VHXwIDAQABAoIBAEGjrUXCd8O4X8eC
                BhfbV2VQ9sDBj8iZ+c2lVDfAb6eSNhWgYaJDCbH9O4TFNyg8FEHqMXDlxzFNjYTy
                7gEKfx1+RBZoNjLpD7eAHHKLKS7pDCuDcKU3dEYEyWzK9fOp5IbNVGVx3YNJOb6H
                3K+VkUjp2PHj+vYKwACQZ+LyR0KvGlz3BHQ4lmOWVbKbKmVLsNYB+5y4Dk2FVKhm
                HO1cInDO0gzSyq9SJxJJ1F9KJpJK8YWfxKOyO6GkKgZlKqOhV0N+7T3D7w5VTYQE
                MK+NOhiOpGKRe7F+w6i3L2gKG0Y6kqZ+QxD1E8qX3T2D6v3I3NXq7f2+l9qvpgvF
                t3IbYQECgYEA+W2g5q8vgKY9C8OQUK7qk8LbzP7y0D3hKqKz2WvF9A8jP7Z7TQl2
                k1UvYzF4TGnO1+Y5nDGkLKYnO4B8OVQj4LX8X7JNyKy9lKhKlL8TqJ2D7cKIgXQs
                QYzq9oSyX3WYLJy9YNhBGZQZq8kJ3jZYl6N8X5JGQnQlPwQ4k5QcDgECgYEA6c1s
                3aDl0g6Y6UEFp+U7E3pf3K2LGK4T9BgOGnp2l5cKZ2I9fqOqN4AXOqO0YqvVLqGN
                5qKS9XWQNGlQj2TGnLQ+w5VKkDd8TqKzgV9dKKqYoZ4LvZK3KYBgY7v2Y9C1K6YE
                D8GqU4SvKqBTYV5E7QAhDWB5y8gWXZnJ2XvZA78CgYEAvY9z6G+YGgXCyK7QT5T1
                K3PVqhCdKE1M8pTv9G8jf9xJZl8lUqHqLO2tYCE2Z+7qDwP1q8JEsN7PwQoNT6K3
                fG+y4c2yG6K+4QZ4Nj3qeT2QFyYqz2OhP1j8lUqHqLO2tYCE2Z+7qDwP1q8JEsN7
                PwQoNT6K3fG+y4c2yG6K+4QZ4Nj3qeT2QFyYqz2OhP1j8lUqHqLO2tYCE2Z+7qBA
                -----END RSA PRIVATE KEY-----
                
    scim:
      users:
        - admin|admin|admin@test.org|admin|admin|uaa.admin
      user:
        override: true
        
    oauth:
      clients:
        admin:
          authorized-grant-types: client_credentials
          scope: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write
          authorities: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write
          secret: admin-secret
        cf:
          override: true
          authorized-grant-types: password,refresh_token
          scope: cloud_controller.read,cloud_controller.write,openid,password.write,scim.userids,cloud_controller.admin,scim.read,scim.write
          authorities: uaa.none
          access-token-validity: 600
          refresh-token-validity: 2592000
          
    zones:
      internal:
        hostnames:
          - uaa.uaa-system.svc.cluster.local
          - localhost
          - 127.0.0.1
