apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
- path: scripts/assets/templates/uaa
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry/uaa
      ref: develop
    includePaths:
    - k8s/templates/**/*
    newRootPath: k8s/templates
