apiVersion: v1
kind: Secret
metadata:
  name: image-registry-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxNzIuMTkuMC4xOjUwMDAiOnsidXNlcm5hbWUiOiIiLCJwYXNzd29yZCI6IiIsImF1dGgiOiIifX19