apiVersion: v1
kind: Namespace
metadata:
  name: uaa-system
---
apiVersion: v1
kind: Service
metadata:
  name: uaa
  namespace: uaa-system
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uaa-route
  namespace: uaa-system
  labels:
    app.kubernetes.io/name: uaa
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: korifi
    namespace: korifi-gateway
  hostnames:
  - "uaa-127-0-0-1.nip.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: uaa
      port: 8080
      weight: 1