apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-config
  namespace: uaa-system
  labels:
    app.kubernetes.io/component: authorization_server
    app.kubernetes.io/instance: uaa-standalone
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: uaa
    app.kubernetes.io/part-of: uaa
    app.kubernetes.io/version: 77.14.0
  annotations:
    kapp.k14s.io/versioned: ""
data:
  log4j2.properties: |-
    status = error
    dest = err
    name = UaaLog

    property.log_pattern=[%d{yyyy-MM-dd'T'HH:mm:ss.nnnnnn}{GMT+0}Z] uaa%X{context} - %pid [%t] .... %5p --- %c{1}: %replace{%m}{(?<=password=|client_secret=)([^&]*)}{<redacted>}%n

    appender.uaaDefaultAppender.type = Console
    appender.uaaDefaultAppender.name = UaaDefaultAppender
    appender.uaaDefaultAppender.layout.type = PatternLayout
    appender.uaaDefaultAppender.layout.pattern = [UAA] ${log_pattern}

    appender.uaaAuditAppender.type = Console
    appender.uaaAuditAppender.name = UaaAuditAppender
    appender.uaaAuditAppender.layout.type = PatternLayout
    appender.uaaAuditAppender.layout.pattern = [UAA_AUDIT] ${log_pattern}

    rootLogger.level = info
    rootLogger.appenderRef.uaaDefaultAppender.ref = UaaDefaultAppender

    logger.UAAAudit.name = UAA.Audit
    logger.UAAAudit.level = info
    logger.UAAAudit.additivity = true
    logger.UAAAudit.appenderRef.auditEventLog.ref = UaaAuditAppender

    logger.cfIdentity.name = org.cloudfoundry.identity
    logger.cfIdentity.level = info
    logger.cfIdentity.additivity = false
    logger.cfIdentity.appenderRef.uaaDefaultAppender.ref = UaaDefaultAppender
  uaa.yml: |
    issuer:
      uri: http://uaa-127-0-0-1.nip.io/uaa
    LOGIN_SECRET: loginsecret
    database:
      maxactive: 100
      maxidle: 10
      minidle: 0
      removeabandoned: false
      logabandoned: true
      abandonedtimeout: 300
      url: jdbc:hsqldb:mem:uaa
    smtp:
      host: null
      port: 25
      starttls: null
      from_address: null
      sslprotocols: null
    login:
      saml:
        activeKeyId: uaa-saml-key-1
        keys:
          # SAML signing certificate and private key - Valid until 2035-10-01
          # Certificate Subject: CN=SAML Signing Certificate 
          # Self-signed certificate for UAA SAML Service Provider functionality
          uaa-saml-key-1:
            key: |
              -----BEGIN PRIVATE KEY-----
              MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDBUufXuXWdLdfv
              JarjfBIKkh88SpkOSsVuulAwzF+y0tg5W+3Q0fH6j7AXwVNr0NHE5/CYSdYHueWZ
              VW0Yl1GYtJOl3hDYnxGKDv0XPcGdk8SFFoiDOFvVTyd3B/s63Rn77QgynZMdG873
              FDlzrQk8VXnABjJnDrs5pHlw55qknlCLw0BPOY3kpPcuDoejZBGNKA3nfAwCncKH
              nfbSLa+zbXnZ7F+AHs6E4m5qZKH3QJrVBfZqUcL40I/CnUOO+lYRqwKP5SR/3jfr
              WTzvM+NMUaSK3mk0BZ9+kf+Fmk4AW68DWbG6sTPIsM9/N9kKp3EYaufg83FGKR58
              ZgMaZwJlAgMBAAECggEABH+eX3m0T+0CKlFxEYwQi2htC6UcvKVmxLXXKduHmoyn
              dWY7OXG5NMBlM5hPDaI1T2SqR5DoRxO/UPsY58qVnn0NNn3dXH0PFmxU3VaVi8ol
              d4dXs9363RLTc0SfRvZgJWmVmD/sbW/5N+yjjZqILXw7sgky4Q0JtESsgsEQ6yWt
              laounYidgEMKLX3x8x48HgTvgqplT47SSwN2XPevVZfbC1BGbtt/ziWSvLbi0ond
              mXhPTfzWvTJQ8lgjWQfsE/r5Ygc+XCaH2JqN7mseORnNPQH6V7JUAp7wtvKnAvFN
              c7gSMMibtUw027XQsv7EtUa+gMry/u/kp9muFFwcfQKBgQDe2B6v6eDXJcnecNfB
              IKm8SkIXYAx1THgwVD2n3hW+o9LOGP9NOKqtdIbsNPowO1Ej6DBRGUdrF6DMN86P
              gpkXO10JU/etCt/LADaotukWml18vJyFcM2kEoAXMMC72+Kc5r30tGKhuGJctDpf
              iGSPKaPijo1MBNA4iS7dDxt1CwKBgQDeFmONQQxT5DMnbBzZeB8DzWGX6v90z04N
              cbJVQqXoc/U2jYEsnL4MTr27PFyWwwnL+nJ5Hfvz0uiQOzkvEV7ggt1wwZ0o/wAa
              zt2pti9/RVajOKZiY+yogOTcxGvKnUkpcSBetOye1mfwNHdyUoINEUhRG8QFCyTt
              YRz5DHAsTwKBgAvQBQBqM2L0O9kwvh8criKvBQXcL4zgOtbFAGevnBN496m5JX9g
              a5u6O5S10jVQT6LJohYKcwC4RevNYYO19ouGuA3Qh6aClw5ZuowC9iQelqoQDXP9
              YMk7udKA4RaUN1T93j/kd/3+migz3YxG3J3CJU/TIqZO8wKsMvHA5UG1AoGBAIXM
              /1VO51pzlc4eeJMcp7LmvfGFBzsc2m2HHmX3rXUKx6WCQ1zZYjaQCgcQKsg54WEf
              FnCZ+/2+B5c91wngcUTaEwen3kOgvjNohmuE88C9yaC0tKl6gk5SuY+4VyjO8hEh
              strcLeLUUfKJ6Zza0LeGvgb/r21KdYj+hTIWqE5JAoGBANuQ94b37lY7a+xeBm1g
              IWS/159c6jNA6fFA1ysRw/+Mtih5iSpJa25ZU4GQWibcnxpTaMOgUDikJPGg07R+
              rBgEypO3Wc1/DW7lHIlPqCWOI3bS+TmjHGwsT1eRTT/e1J3lWzjMg0PhAh3yNG+A
              gW1boJTUmKCsaZu61Ua8HhiZ
              -----END PRIVATE KEY-----
            certificate: |
              -----BEGIN CERTIFICATE-----
              MIIDJzCCAg+gAwIBAgIUXCh/3MJdYQQ1ric53qUiRBWXeYEwDQYJKoZIhvcNAQEL
              BQAwIzEhMB8GA1UEAwwYU0FNTCBTaWduaW5nIENlcnRpZmljYXRlMB4XDTI1MTAw
              MzE3MjI0OFoXDTM1MTAwMTE3MjI0OFowIzEhMB8GA1UEAwwYU0FNTCBTaWduaW5n
              IENlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwVLn
              17l1nS3X7yWq43wSCpIfPEqZDkrFbrpQMMxfstLYOVvt0NHx+o+wF8FTa9DRxOfw
              mEnWB7nlmVVtGJdRmLSTpd4Q2J8Rig79Fz3BnZPEhRaIgzhb1U8ndwf7Ot0Z++0I
              Mp2THRvO9xQ5c60JPFV5wAYyZw67OaR5cOeapJ5Qi8NATzmN5KT3Lg6Ho2QRjSgN
              53wMAp3Ch5320i2vs2152exfgB7OhOJuamSh90Ca1QX2alHC+NCPwp1DjvpWEasC
              j+Ukf94361k87zPjTFGkit5pNAWffpH/hZpOAFuvA1mxurEzyLDPfzfZCqdxGGrn
              4PNxRikefGYDGmcCZQIDAQABo1MwUTAdBgNVHQ4EFgQUIpaDkn0ieEGOLPH/3Sxa
              a0EUvNgwHwYDVR0jBBgwFoAUIpaDkn0ieEGOLPH/3Sxaa0EUvNgwDwYDVR0TAQH/
              BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAdmSImdGcmZUxdCRpTOBzEqXx8zXI
              1lyiaeqTC3c0oh0Sh2Z77myrEvnb2idLwHLzjoC3RQAk2rgH3wcJ/ty3KafnsX8b
              Qy75dVDYsEPa1y8YNatFmxx6iQ8boTsmGhUTENKKWBd22fizc3+50w8Yi9PX6pXz
              HRwZKfs1Nsxlv9NqInz8b5RBJdQet0i6rEU/YQvGmLq3A0QttaQZp+cftzO9J0eo
              gMjZfizAPfMq1hTzZrS0jnSO03U1MVbpTZzoZoT8Hx0UDJX3YXzNN0squjWV32Kt
              yWVVSSlVCTzP8NkboEVMewMlJ7EvFUcG4Jc7q4verCkI23Tw4J7dVckiHg==
              -----END CERTIFICATE-----
            passphrase: ""
    oauth:
      client:
        override: true
      clients:
        admin:
          authorized-grant-types: client_credentials
          authorities: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write
        cf:
          access-token-validity: 1200
          authorities: uaa.none
          authorized-grant-types: password,refresh_token,urn:ietf:params:oauth:grant-type:jwt-bearer
          override: true
          refresh-token-validity: 2592000
          scope: network.admin,network.write,cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write,doppler.firehose,uaa.user,routing.router_groups.read,routing.router_groups.write,cloud_controller.admin_read_only,cloud_controller.global_auditor,perm.admin,clients.read
          secret: ''
    scim:
      users:
      - admin|admin_secret|admin@admin.admin|Admin|Admin|cloud_controller.admin,scim.read,scim.write,doppler.firehose,openid,routing.router_groups.read,routing.router_groups.write,network.admin,clients.read